spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MV_STORE=TRUE
    username: admin
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
